from blinkt import NUM_PIXELS

NUMBER_OF_PIXELS = NUM_PIXELS

MAXIMUM_COLOUR_INTENSITY = 255

RED = (MAXIMUM_COLOUR_INTENSITY, 0, 0)

YELLOW = (MAXIMUM_COLOUR_INTENSITY, MAXIMUM_COLOUR_INTENSITY, 0)
TURQUISE = (0, MAXIMUM_COLOUR_INTENSITY, MAXIMUM_COLOUR_INTENSITY)

WHITE = (MAXIMUM_COLOUR_INTENSITY, MAXIMUM_COLOUR_INTENSITY, MAXIMUM_COLOUR_INTENSITY)